package ecode

import "go-porter/pkg/core/pkg/xerror"

var (
	// business errors:
	//通用错误 需要warp错误信息
	ErrServer        = xerror.Error(200101, "服务器忙,稍后再来试一试")
	ErrAuthorization = xerror.Error(200104, "签名信息错误")
	ErrUrlSign       = xerror.Error(200105, "参数签名错误")
	ErrCacheSet      = xerror.Error(200105, "设置缓存失败")
	ErrCacheGet      = xerror.Error(200105, "获取缓存失败")
	ErrCacheDel      = xerror.Error(200105, "删除缓存失败")
	ErrCacheNotExist = xerror.Error(200105, "缓存不存在")
	ErrResubmit      = xerror.Error(200105, "请勿重复提交")

	ErrHashIdsEncode           = xerror.Error(200105, "HashID 加密失败")
	ErrHashIdsDxerror          = xerror.Error(200105, "HashID 解密失败")
	ErrRBAC                    = xerror.Error(200105, "暂无访问权限")
	ErrRedisConnect            = xerror.Error(200105, "Redis 连接失败")
	ErrMySQLConnect            = xerror.Error(200105, "MySQL 连接失败")
	ErrWriteConfig             = xerror.Error(200105, "写入配置文件失败")
	ErrSendEmail               = xerror.Error(200105, "发送邮件失败")
	ErrMySQLExec               = xerror.Error(200105, "SQL 执行失败")
	ErrGoVersion               = xerror.Error(200105, "Go 版本不满足要求")
	ErrSocketConnect           = xerror.Error(200105, "Socket 未连接")
	ErrSocketSend              = xerror.Error(200105, "Socket 消息发送失败")
	ErrAuthorizedCreate        = xerror.Error(200105, "创建调用方失败")
	ErrAuthorizedList          = xerror.Error(200105, "获取调用方列表失败")
	ErrAuthorizedDelete        = xerror.Error(200105, "删除调用方失败")
	ErrAuthorizedUpdate        = xerror.Error(200105, "更新调用方失败")
	ErrAuthorizedDetail        = xerror.Error(200105, "获取调用方详情失败")
	ErrAuthorizedCreateAPI     = xerror.Error(200105, "创建调用方 API 地址失败")
	ErrAuthorizedListAPI       = xerror.Error(200105, "获取调用方 API 地址列表失败")
	ErrAuthorizedDeleteAPI     = xerror.Error(200105, "删除调用方 API 地址失败")
	ErrAdminCreate             = xerror.Error(200105, "创建管理员失败")
	ErrAdminList               = xerror.Error(200105, "获取管理员列表失败")
	ErrAdminDelete             = xerror.Error(200105, "删除管理员失败")
	ErrAdminUpdate             = xerror.Error(200105, "更新管理员失败")
	ErrAdminResetPassword      = xerror.Error(200105, "重置密码失败")
	ErrAdminLogin              = xerror.Error(200105, "登录失败")
	ErrAdminLogOut             = xerror.Error(200105, "退出失败")
	ErrAdminModifyPassword     = xerror.Error(200105, "修改密码失败")
	ErrAdminModifyPersonalInfo = xerror.Error(200105, "修改个人信息失败")
	ErrAdminMenuList           = xerror.Error(200105, "获取管理员菜单授权列表失败")
	ErrAdminMenuCreate         = xerror.Error(200105, "管理员菜单授权失败")
	ErrAdminOffline            = xerror.Error(200105, "下线管理员失败")
	ErrAdminDetail             = xerror.Error(200105, "获取个人信息失败")
)
